### ISSUE TITLE
social media icons size bug

### ISSUE THREAD

**Issue by tivasyk** [aterenin/minima-reboot#1]
currently the size of the _\_includes/icon-github.svg_ for the footer is specified in the svg and not controlled in css:

`<svg viewBox="0 0 16 16" width="16px" height="16px" xmlns="http://www.w3.org/2000/svg">`

adding icons that don't contain a hard-coded width and height results in the icons taking up 100% of the available `<div>` space.

proposed fix:

* add css to control the social media icons size;
* (optional) remove the width and height parameters from the bundled icon-github.svg.

**Comment by aterenin** [comment]
This mirrors a former Minima behavior, as the icon is forked from there.

There's a case to be made for changing this by altering `_config.yml` to include two more parameters, which get passed in to the icon via the include. The proposed fix would then look like

```yml
footer_icons:
  - username: aterenin/minima-reboot/
    url: https://github.com/aterenin/minima-reboot/
    icon: icon-github.svg
    icon_height: 16px
    icon_width: 16px
```

which would then be passed into `includes/icon-github.svg` by Liquid.

However, this requires the user to ensure that their svg icons in `includes` are specially formatted for use with the theme, containing Liquid tags such as `{{ icon_height }}` or similar.

Since the theme does not provide icons other than the GitHub icon and expects users to provide their own SVG files anyway, perhaps it's simpler and more minimal to not add this option, and simply expect the users to modify their SVGs as needed.

I particular, you could just create a file `includes/icon-github.svg` containing whatever you want, which will override the theme's icon if loaded with `remote_theme: aterenin/minima-reboot`.

Let me know your thoughts on which of these sounds better.

**Comment by tivasyk** [comment]
i had no problem adding width and height declarations to my svg's. however every other user with side-loaded icons will have the same issues; also, providing a http(s) link to an external svg doesn't work.

i guess, the solution, and the need of one for minima-reboot in the first place will depend on whether it's a standalone theme or one that keeps minima as upstream source.

**Comment by aterenin** [comment]
After more thought, the right way to handle this is for the user to simply add a file in the `includes` directory in their site. This will cause Jekyll to build that site with the user's file instead of the one supplied by the theme, and is a more generic solution than adding features to `_config.yml`.

**Comment by aterenin** [comment]
To add one further quick thought - in my own personal website's code, I use

```
{{ icon-github | replace: "16px", "36px" }}
```

to correctly resize the GitHub icon. This is another way to achieve the same effect without adding a new file to `includes`.

**Comment by tivasyk** [comment]
thank you! although i've long since fixed my personal issue by editing the
svg's i use, this will help others.

ivas tarasyk (tivasyk)

google talk: tivasyk@gmail.com

відповідь на питання про сенс життя, існування всесвіту і взагалі…
www.tivasyk.info <http://www.tivasyk.info/2011/09/blog-post_4990.html>


Le lun. 2 mars 2020 à 19:51, Alexander Terenin <notifications@github.com> a
écrit :
